// Full-body horse images matching genetics — generated by phenotype
// Each image: full horse standing side-profile, coat color + pattern from genotype

const PHENO_IMAGES = {
  // Base colors (solid)
  bay:           "https://media.base44.com/images/public/69b44c69482b4d9133223b0e/3ce1caa4e_generated_image.png",
  bayTobiano:    "https://media.base44.com/images/public/69b44c69482b4d9133223b0e/f74c2c196_generated_image.png",
  chestnut:      "https://media.base44.com/images/public/69b44c69482b4d9133223b0e/feec03638_generated_image.png",
  chestnutTobiano: "https://media.base44.com/images/public/69b44c69482b4d9133223b0e/ffceff460_generated_image.png",
  black:         "https://media.base44.com/images/public/69b44c69482b4d9133223b0e/5c3e05121_generated_image.png",
  blackTobiano:  "https://media.base44.com/images/public/69b44c69482b4d9133223b0e/5d61f9efe_generated_image.png",
  grey:          "https://media.base44.com/images/public/69b44c69482b4d9133223b0e/9f3c42efa_generated_image.png",
  palomino:      "https://media.base44.com/images/public/69b44c69482b4d9133223b0e/918a902cc_generated_image.png",
  buckskin:      "https://media.base44.com/images/public/69b44c69482b4d9133223b0e/ebca1607c_generated_image.png",
  blueRoan:      "https://media.base44.com/images/public/69b44c69482b4d9133223b0e/e02ae90f1_generated_image.png",
  silverBlack:   "https://media.base44.com/images/public/69b44c69482b4d9133223b0e/bffd08910_generated_image.png",
  perlino:       "https://media.base44.com/images/public/69b44c69482b4d9133223b0e/efcde8ad6_generated_image.png",
};

// Map full genotype → matching phenotype image
export function getHorsePhotoUrl(genotype, _horseId = "") {
  if (!genotype) return PHENO_IMAGES.bay;

  const isBlack  = genotype.extension !== "ee";
  const hasAgouti = genotype.agouti !== "aa";
  const hasCream  = genotype.cream === "Crn";
  const doubleCream = genotype.cream === "CrCr";
  const isGrey    = genotype.grey === "GG" || genotype.grey === "Gg";
  const hasTobiano = genotype.tobiano && genotype.tobiano !== "nn";
  const hasRoan   = genotype.roan === "RNn" || genotype.roan === "RNRN";
  const hasSilver = genotype.silver === "Zz" || genotype.silver === "ZZ";

  // Grey masks everything
  if (isGrey) return PHENO_IMAGES.grey;

  // Double cream → perlino/cremello
  if (doubleCream) return PHENO_IMAGES.perlino;

  // Roan takes precedence over tobiano for visual clarity
  if (hasRoan && !hasCream) return PHENO_IMAGES.blueRoan;

  if (!isBlack) {
    // Chestnut family (ee)
    if (hasCream) return PHENO_IMAGES.palomino; // Palomino
    if (hasTobiano) return PHENO_IMAGES.chestnutTobiano;
    return PHENO_IMAGES.chestnut;
  }

  if (hasAgouti) {
    // Bay family
    if (hasCream) return PHENO_IMAGES.buckskin; // Buckskin
    if (hasTobiano) return PHENO_IMAGES.bayTobiano;
    return PHENO_IMAGES.bay;
  }

  // Black family (E_ aa)
  if (hasSilver) return PHENO_IMAGES.silverBlack;
  if (hasTobiano) return PHENO_IMAGES.blackTobiano;
  return PHENO_IMAGES.black;
}