// Full-body horse images matching genetics — generated by phenotype
// Includes pie patterns (tobiano, sabino, splash, overo), roan, and breed-specific coats
// Foals (0-3 ans) have dedicated images per pattern type

const PHENO_IMAGES = {
  // === Solid base colors (adult) ===
  bay:           "https://media.base44.com/images/public/69b44c69482b4d9133223b0e/3ce1caa4e_generated_image.png",
  chestnut:      "https://media.base44.com/images/public/69b44c69482b4d9133223b0e/feec03638_generated_image.png",
  black:         "https://media.base44.com/images/public/69b44c69482b4d9133223b0e/5c3e05121_generated_image.png",
  grey:          "https://media.base44.com/images/public/69b44c69482b4d9133223b0e/9f3c42efa_generated_image.png",
  palomino:      "https://media.base44.com/images/public/69b44c69482b4d9133223b0e/918a902cc_generated_image.png",
  buckskin:      "https://media.base44.com/images/public/69b44c69482b4d9133223b0e/ebca1607c_generated_image.png",
  silverBlack:   "https://media.base44.com/images/public/69b44c69482b4d9133223b0e/bffd08910_generated_image.png",
  perlino:       "https://media.base44.com/images/public/69b44c69482b4d9133223b0e/efcde8ad6_generated_image.png",
  // === Roan (adult) — trois variantes : bai granité, alezan granité (aubère), noir granité (gris fer) ===
  bayRoan:       "https://media.base44.com/images/public/69b44c69482b4d9133223b0e/6e4725486_generated_image.png",
  chestnutRoan:  "https://media.base44.com/images/public/69b44c69482b4d9133223b0e/2e846bac7_generated_image.png",
  blueRoan:      "https://media.base44.com/images/public/69b44c69482b4d9133223b0e/f3a1831ea_generated_image.png",
  // === Breed-specific (adult) ===
  haflinger:     "https://media.base44.com/images/public/69b44c69482b4d9133223b0e/a48cad7cf_generated_image.png",
  appaloosa:     "https://media.base44.com/images/public/69b44c69482b4d9133223b0e/5ffc5983f_generated_image.png",
  // === Tobiano patterns (adult) ===
  bayTobiano:      "https://media.base44.com/images/public/69b44c69482b4d9133223b0e/f74c2c196_generated_image.png",
  chestnutTobiano: "https://media.base44.com/images/public/69b44c69482b4d9133223b0e/ffceff460_generated_image.png",
  blackTobiano:    "https://media.base44.com/images/public/69b44c69482b4d9133223b0e/5d61f9efe_generated_image.png",
  // === Sabino patterns (adult) ===
  baySabino:     "https://media.base44.com/images/public/69b44c69482b4d9133223b0e/230240843_generated_image.png",
  chestnutSabino:"https://media.base44.com/images/public/69b44c69482b4d9133223b0e/ab74dace5_generated_image.png",
  blackSabino:   "https://media.base44.com/images/public/69b44c69482b4d9133223b0e/c4bcf22d7_generated_image.png",
  // === Splash patterns (adult) ===
  baySplash:       "https://media.base44.com/images/public/69b44c69482b4d9133223b0e/6f553736f_generated_image.png",
  chestnutSplash:  "https://media.base44.com/images/public/69b44c69482b4d9133223b0e/fd71658c6_generated_image.png",
  blackSplash:     "https://media.base44.com/images/public/69b44c69482b4d9133223b0e/2bea1987a_generated_image.png",
  // === Overo patterns (adult) ===
  bayOvero:      "https://media.base44.com/images/public/69b44c69482b4d9133223b0e/401a75f19_generated_image.png",
  chestnutOvero: "https://media.base44.com/images/public/69b44c69482b4d9133223b0e/c08398296_generated_image.png",
  blackOvero:    "https://media.base44.com/images/public/69b44c69482b4d9133223b0e/6c466272e_generated_image.png",
  // === Foals — solid colors ===
  foalBay:       "https://media.base44.com/images/public/69b44c69482b4d9133223b0e/fefb187c9_generated_image.png",
  foalChestnut:  "https://media.base44.com/images/public/69b44c69482b4d9133223b0e/020485ebd_generated_image.png",
  foalBlack:     "https://media.base44.com/images/public/69b44c69482b4d9133223b0e/c3f85e151_generated_image.png",
  foalGrey:      "https://media.base44.com/images/public/69b44c69482b4d9133223b0e/4e0aacdcc_generated_image.png",
  // === Foals — patterns ===
  foalTobiano:   "https://media.base44.com/images/public/69b44c69482b4d9133223b0e/a1313c24d_generated_image.png",
  foalSabino:    "https://media.base44.com/images/public/69b44c69482b4d9133223b0e/073d7d401_generated_image.png",
  foalOvero:     "https://media.base44.com/images/public/69b44c69482b4d9133223b0e/59a3b6c13_generated_image.png",
  foalSplash:    "https://media.base44.com/images/public/69b44c69482b4d9133223b0e/7ed5d2f14_generated_image.png",
  foalRoan:      "https://media.base44.com/images/public/69b44c69482b4d9133223b0e/e18ed4e27_generated_image.png",
};

// Determine base color category from genotype
function getBaseCategory(genotype) {
  if (!genotype) return "bay";
  const isBlack = genotype.extension !== "ee";
  const hasAgouti = genotype.agouti !== "aa";
  const cream = genotype.cream;
  const hasSilver = genotype.silver === "Zz" || genotype.silver === "ZZ";

  // Pearl: double dilutions (même gamme visuelle que double crème)
  if (cream === "prlprl" || cream === "Crprl") return "perlino";
  if (cream === "CrCr") return "perlino";
  // Single cream
  const hasCream = cream === "Crn";
  if (!isBlack) {
    return hasCream ? "palomino" : "chestnut";
  }
  if (hasAgouti) {
    return hasCream ? "buckskin" : "bay";
  }
  // Black family
  if (hasSilver) return "silverBlack";
  return "black";
}

// Helper: pick pattern+base image from a mapping object
function pickByBase(base, map) {
  if (base === "chestnut" || base === "palomino") return map.chestnut;
  if (base === "black" || base === "silverBlack") return map.black;
  return map.bay;
}

// Renvoie les infos de robe : couleur affichée + couleur de naissance sous-jacente si gris + isGrey
// Utile pour que les chevaux gris montrent aussi leurs patterns cachés dans le visuel
export function getCoatInfo(genotype) {
  if (!genotype) return { display: "Inconnu", birth: "Inconnu", isGrey: false };
  const isGrey = genotype.grey === "GG" || genotype.grey === "Gg";
  const hasTobiano = genotype.tobiano && genotype.tobiano !== "nn";
  const hasSabino = genotype.sabino && genotype.sabino !== "nn";
  const hasSplash = genotype.splash && genotype.splash !== "nn";
  const hasOvero = genotype.overo && genotype.overo !== "nn";
  const hasRoan = genotype.roan === "RNn" || genotype.roan === "RNRN";
  const hasMushroom = genotype.mushroom === "mumu";
  const isBlack = genotype.extension !== "ee";
  const hasAgouti = genotype.agouti !== "aa";
  const cream = genotype.cream;
  let base = isBlack ? (hasAgouti ? "bai" : "noir") : "alezan";
  // Double dilutions : crème ou perle
  if (cream === "prlprl") {
    base = isBlack ? (hasAgouti ? "double perle bai" : "double perle noir") : "double perle alezan";
  } else if (cream === "Crprl") {
    base = isBlack ? (hasAgouti ? "isabelle perle" : "smoky black perle") : "palomino perle";
  } else if (cream === "CrCr") {
    base = isBlack ? (hasAgouti ? "perlino" : "cremello") : "cremello";
  } else if (cream === "Crn") {
    base = isBlack ? (hasAgouti ? "isabelle" : "smoky") : "palomino";
  }
  if (hasMushroom && (base === "alezan" || base === "bai")) base = (base === "alezan" ? "ale" : "b") + "zan mushroom";
  const parts = [base];
  if (hasRoan) parts.push(isBlack ? "gris fer" : "granité");
  if (hasTobiano) parts.push("tobiano");
  else if (hasOvero) parts.push("overo");
  if (hasSplash) parts.push("splash");
  if (hasSabino) parts.push("sabino");
  const hasDun = genotype.dun && genotype.dun !== 'nd2nd2';
  const birth = [...new Set(parts)].join(" ");
  return { display: isGrey ? "Gris" : birth, birth: isGrey ? birth : birth, isGrey, primitiveMarkings: !isGrey && hasDun };
}

// Map full genotype + breed + age → matching phenotype image
// age < 3 → foal image, age >= 3 → adult image
export function getHorsePhotoUrl(genotype, horseId = "", breed, age) {
  if (!genotype) return PHENO_IMAGES.bay;

  const isFoal = typeof age === "number" && age < 3;

  const isGrey = genotype.grey === "GG" || genotype.grey === "Gg";
  const doubleCream = genotype.cream === "CrCr" || genotype.cream === "Crprl" || genotype.cream === "prlprl";
  const hasRoan = genotype.roan === "RNn" || genotype.roan === "RNRN";
  const hasTobiano = genotype.tobiano && genotype.tobiano !== "nn";
  const hasSabino = genotype.sabino && genotype.sabino !== "nn";
  const hasSplash = genotype.splash && genotype.splash !== "nn";
  const hasOvero = genotype.overo && genotype.overo !== "nn";

  // === Breed-specific overrides (highest priority) ===
  // Friesian: purebred is ALWAYS black
  if (breed === "Friesian") return isFoal ? PHENO_IMAGES.foalBlack : PHENO_IMAGES.black;
  // Appaloosa: leopard spots are the defining visual trait
  if (breed === "Appaloosa" && !isGrey) return isFoal ? PHENO_IMAGES.foalRoan : PHENO_IMAGES.appaloosa;
  // Haflinger: chestnut with flaxen mane — unique look
  if (breed === "Haflinger" && !isGrey) return isFoal ? PHENO_IMAGES.foalChestnut : PHENO_IMAGES.haflinger;

  // === Grey masks everything ===
  if (isGrey) return isFoal ? PHENO_IMAGES.foalGrey : PHENO_IMAGES.grey;

  // === Foals: per-pattern images ===
  if (isFoal) {
    if (hasTobiano) return PHENO_IMAGES.foalTobiano;
    if (hasOvero) return PHENO_IMAGES.foalOvero;
    if (hasSplash) return PHENO_IMAGES.foalSplash;
    if (hasSabino) return PHENO_IMAGES.foalSabino;
    if (hasRoan) return PHENO_IMAGES.foalRoan;
    // Solid foal colors
    const base = getBaseCategory(genotype);
    if (base === "chestnut" || base === "palomino") return PHENO_IMAGES.foalChestnut;
    if (base === "black" || base === "silverBlack") return PHENO_IMAGES.foalBlack;
    return PHENO_IMAGES.foalBay;
  }

  // === Adult: double cream → perlino/cremello ===
  if (doubleCream) return PHENO_IMAGES.perlino;

  const base = getBaseCategory(genotype);

  // === Roan ===
  if (hasRoan && !hasTobiano) {
    // Trois variantes : noir granité (gris fer), alezan granité (aubère), bai granité
    if (base === "black" || base === "silverBlack") return PHENO_IMAGES.blueRoan;
    if (base === "chestnut" || base === "palomino") return PHENO_IMAGES.chestnutRoan;
    return PHENO_IMAGES.bayRoan;
  }

  // === Pie patterns: tobiano > overo > splash > sabino ===
  if (hasTobiano) {
    return pickByBase(base, {
      chestnut: PHENO_IMAGES.chestnutTobiano,
      black: PHENO_IMAGES.blackTobiano,
      bay: PHENO_IMAGES.bayTobiano,
    });
  }

  if (hasOvero) {
    return pickByBase(base, {
      chestnut: PHENO_IMAGES.chestnutOvero,
      black: PHENO_IMAGES.blackOvero,
      bay: PHENO_IMAGES.bayOvero,
    });
  }

  if (hasSplash) {
    return pickByBase(base, {
      chestnut: PHENO_IMAGES.chestnutSplash,
      black: PHENO_IMAGES.blackSplash,
      bay: PHENO_IMAGES.baySplash,
    });
  }

  if (hasSabino) {
    return pickByBase(base, {
      chestnut: PHENO_IMAGES.chestnutSabino,
      black: PHENO_IMAGES.blackSabino,
      bay: PHENO_IMAGES.baySabino,
    });
  }

  // === Solid base colors ===
  return PHENO_IMAGES[base] || PHENO_IMAGES.bay;
}