// Paddock type configuration - effects and visuals
export const PADDOCK_TYPES = {
  pasture: {
    label: "Pasture",
    icon: "🌿",
    color: "from-green-400 to-emerald-500",
    bg: "bg-green-50",
    border: "border-green-200",
    textColor: "text-green-700",
    morale_bonus: 10,
    energy_recovery_rate: 12,
    capacity: 6,
    description: "Large green space. Excellent for morale and natural recovery.",
  },
  training: {
    label: "Training",
    icon: "🏋️",
    color: "from-blue-400 to-blue-600",
    bg: "bg-blue-50",
    border: "border-blue-200",
    textColor: "text-blue-700",
    morale_bonus: 0,
    energy_recovery_rate: 6,
    capacity: 3,
    description: "Paddock equipped for effort. Slower recovery but increased performance.",
  },
  recovery: {
    label: "Rest",
    icon: "💤",
    color: "from-purple-400 to-violet-500",
    bg: "bg-purple-50",
    border: "border-purple-200",
    textColor: "text-purple-700",
    morale_bonus: 5,
    energy_recovery_rate: 20,
    capacity: 4,
    description: "Calm and comfortable paddock. Maximum energy recovery.",
  },
  quarantine: {
    label: "Quarantine",
    icon: "🔒",
    color: "from-red-400 to-rose-500",
    bg: "bg-red-50",
    border: "border-red-200",
    textColor: "text-red-700",
    morale_bonus: -10,
    energy_recovery_rate: 8,
    capacity: 2,
    description: "Sanitary isolation. Reduced morale, prevents disease spread.",
  },
  foaling: {
    label: "Foaling",
    icon: "🐣",
    color: "from-pink-400 to-rose-400",
    bg: "bg-pink-50",
    border: "border-pink-200",
    textColor: "text-pink-700",
    morale_bonus: 15,
    energy_recovery_rate: 14,
    capacity: 2,
    description: "Cozy paddock for pregnant mares. Excellent morale.",
  },
};